apiVersion: apps/v1
kind: Deployment
metadata:
  name: web05-deploy
  labels:
    app: store-app
spec:
  selector:
    matchLabels:
      pod: web05-pod
  template:
    metadata:
      labels:
        pod: web05-pod
    spec:
      containers:
      - image: nginx
        name: web-app


        