apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql.conf: |
    [mysqld]
    port=3306
    socket=/tmp/mysql.sock
    key_buffer_size=16M
    max_allowed_packet=128M
---
apiVersion: v1
kind: Secret
metadata:
  name: db02-secret
type: Opaque
data:
  secret.file: |
    c29tZXN1cGVyc2VjcmV0IGZpbGUgY29udGVudHMgbm9ib2R5IHNob3VsZCBzZWU=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db02-deploy
  labels:
    app: store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: db02-pod
  template:
    metadata:
      labels:
        app: db02-pod
    spec:
      containers:
      - name: db02-pod
        image: busybox:1.22228
        command: ['sh', '-c', "cat /mysql/db-config; cat /mysql/db-secret"]

        volumeMounts:
        - name: db-config
          mountPath: /mysql/db-config
        - name: db-secret
          mountPath: /mysql/db-secret
          readOnly: true

      volumes:
        - name: db-conf
          configMap:
            name: mysql-config
        - name: db-secret
          secret:
            secretName: mysql-secret
