# Exercise 07-05 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db10-deploy 
  labels:
    app: store-app 
spec:
  selector:
    matchLabels:
      pod: db10-pod 
  template:
    metadata:
      labels:
        pod: db10-pod 
        app: prdfin
    spec:
      containers:
      - name: db-app 
        image: redis 
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - prdfin 
            topologyKey: "kubernetes.io/hostname"