# Exercise 16-02 v1.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app02-pod 
  template:
    metadata:
      labels:
        pod: app02-pod 
        app: prdsam
    spec:
      containers:
      - name: busy-app 
        image: busybox:1.28
        command: ["printenv"] 
        args: ["HOSTNAME", "KUBERNETES_PORT"]
        resources: {}

