# Exercise 10-02 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app01-pod 
  template:
    metadata:
      labels:
        pod: app01-pod 
        app: prdsam
    spec:
      containers:
      - name: busy-app 
        image: busybox:1.28
        command: ["/bin/sh"] 
        args: ["-c", "echo Hello from Kubernetes! && sleep 3600"] 

