# Exercise 21-05 v1.0.0
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db03-pvc 
  namespace: database
  labels:
    app: db03-db
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi

