# Exercise 21-05 v1.0.0
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db03-cm 
  namespace: database
  labels:
    app: db03-db 
data:
  POSTGRES_DB: db03-db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: BadPass@1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db03-sts
  namespace: database
  labels:
    app: db03-db
spec:
  serviceName: db03-svc
  selector:
    matchLabels:
      pod: db03-pod
  replicas: 1
  template:
    metadata:
      labels:
        pod: db03-pod
    spec:
      containers:
        - name: postgres
          image: postgres:17.5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db03-cm 
          volumeMounts:
            - name: db03-vol
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db03-vol
          persistentVolumeClaim:
            claimName: db03-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db03-svc
  namespace: database
  labels:
    app: db03-db
spec:
  selector:
    pod: db03-pod
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432
