# Exercise 21-05 v1.0.0
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db03-pv 
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"

