# Exercise 23-05 v1.0.0
#
---
apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
spec:
  type: ClusterIP
  selector:
    name: comm-check-pod 
  ports:
    - protocol: TCP
      name: "http"
      port: 80
      targetPort: 80
