kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db04-pvc
spec:
  storageClassName: managed-nfs-storage # Sets default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
