apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
spec:
  containers:
  - name: my-app-container
    image: busybox
    command: ["sh", "-c", "echo 'Database URL: $DB_URL'; echo 'API Key: $API_KEY'; cat /etc/config/config.properties"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
      readOnly: true
    env:
    - name: DB_URL
      valueFrom:
        configMapKeyRef:
          name: my-app-config
          key: database.url
    - name: API_KEY
      valueFrom:
        configMapKeyRef:
          name: my-app-config
          key: api.key
  volumes:
  - name: config-volume
    configMap:
      name: my-app-config

