# Exercise 12-02 v1.0.0
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-rb
  namespace: prdfin-ns
subjects:
- kind: User
  name: dana_dev 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: read-pods-r
  apiGroup: rbac.authorization.k8s.io


