# Exercise 07-07 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app12-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app12-pod 
  template:
    metadata:
      labels:
        pod: app12-pod 
    spec:
      containers:
      - name: app-app 
        image: busybox:1.28
        command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"] 