# Exercise 07-07 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web12-deploy
  labels:
    app: store-app 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web12-pod
  template:
    metadata:
      labels:
        app: web12-pod
    spec:
      containers:
      - name: web-app
        image: nginx:1.24
      tolerations:
        - key: env
          operator: Equal
          value: prod
          effect: NoSchedule

