# Exercise 20-04 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db10-deploy 
  namespace: database-ns
  labels: 
    app: store-app
    tier: database
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: db10-pod
  template:
    metadata:
      labels:
        pod: db10-pod
        tier: database
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
          - containerPort: 6379
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: db10-svc
  namespace: database-ns
  labels:
    app: store-app
    tier: frontend
spec:
  type: ClusterIP
  selector:
    pod: db10-pod
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
