# Exercise 10-02 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app03-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app03-pod 
  template:
    metadata:
      labels:
        pod: app03-pod 
        app: prdsam
    spec:
      containers:
      - name: busy-app 
        image: busybox:1.28
        env:
          - name: MESSAGE
            value: "Foo goes to a bar"
        command: ["/bin/echo"] 
        args: ["$(MESSAGE)"]

<<<<<<< HEAD
=======

        
>>>>>>> d15e94a3cf9099a5401e825e733b82b2b06e07de
