# Exercise 10-02 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app02-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app04-pod 
  template:
    metadata:
      labels:
        pod: app04-pod 
        app: prdsam
    spec:
      containers:
      - name: app-app 
        image: busybox:1.28
        env:
          - name: MESSAGE
            value: "Foo goes to a bar"
        command: ["env"] 
        env:
          - name: DEMO_VAR
            value: "Environmental variable demo"
          - name: DEBUG_MODE
            value: "true"
