# Exercise 10-06 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app10-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app10-pod 
  template:
    metadata:
      labels:
        pod: app10-pod 
    spec:
      containers:
      - name: app-app 
        image: busybox:1.28
        command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"] 
        env:
          - name: USER
            valueFrom:
              secretKeyRef:
                name: dana-secret 
                key: USERNAME 
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: dana-secret 
                key: PASSWORD

