# Exercise 11-06 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app11-deploy 
  labels:
    app: store-app 
spec:
  replicas: 2  
  selector:
    matchLabels:
      pod: app11-pod 
  template:
    metadata:
      labels:
        pod: app11-pod 
    spec:
      containers:
      - name: app-app 
        image: busybox:1.28
        command: ["sh", "-c", "echo Hello Kubernetes! && sleep 3600"] 
        volumeMounts:
          - name: secret-vol
            mountPath: /etc/config/secret
      volumes: 
        - name: secret-vol
          secret:
            secretName: dana-secret


            