# Exercise 12-02 v1.0.0
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ops-group-role
  namespace: prdfin
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: prdfin
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

