# Exercise 18-05 v1.0.0
#
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: edu
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 32323
    hostPort: 32323 
    protocol: TCP
- role: worker
- role: worker
- role: worker
networking:
  disableDefaultCNI: true
  podSubnet: 10.244.0.0/16

