# Exercise 08-04 v1.0.0
#
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-quotas 
spec:
  hard:
    requests.cpu: "1" 
    requests.memory: 1Gi 
    limits.cpu: "2"
    limits.memory: 2Gi

