# Exercise 32-02 v1.2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web01-deploy
  namespace: dev-ns
  labels:
    app: store-app
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: web01-pod
  template:
    metadata:
      labels:
        pod: web01-pod
        env: development
        version: "2.0"
    spec:
      initContainers:
        - name: init-service-check
          image: busybox:1.36
          command: ["sh", "-c"]
          args: ["echo 'Performing lengthy setup...'; for i in $(seq 1 10); do echo $i; sleep 3; done; echo 'Setup complete.'"]
      containers:
      - name: edu-backend
        image: wmdailey/edu-backend:latest
        ports:
          - containerPort: 5000
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 2
          failureThreshold: 2
        resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: web01-svc
  namespace: dev-ns
  labels:
    app: store-app
spec:
  type: ClusterIP
  selector:
    pod: web01-pod
  ports:
    - name: http
      port: 5000 
      targetPort: 5000 
      protocol: TCP
