# Exercise 15-06 v1.2.0
#
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-quotas
spec:
  hard:
    requests.cpu: "2" 
    requests.memory: 2Gi 
    limits.cpu: "4"
    limits.memory: 8Gi
