# Exercise 08-02 v1.0.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: mem-stress01
spec:
  containers:
    - name: mem-stress
      image: polinux/stress
      command:
        - stress
      args:
        - --vm
        - "1"
        - --vm-bytes
        - 15M
        - --vm-hang
        - "1"
      resources:
        limits:
          memory: 10Mi
        requests:
          memory: 5Mi

