# Exercise 28-03 v1.2.0
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: app-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: db-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: web-ns

