# Exercise 10-04-01
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web04-deploy 
  labels:
    app: store-app
spec:
  replicas: 4
  selector:
    matchLabels:
      pod: web04-pod
  template:
    metadata:
      labels:
        pod: web04-pod 
    spec:
      containers:
        - image: nginx:1.24 
          name: web-app 
          ports:
            - protocol: TCP
              containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: arch
                  operator: In
                  values:
                    - gpu 
              - matchExpressions:
                - key: disktype
                  operator: In
                  values:
                    - hdd 
