# Exercise 10-04-01
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web06-deploy 
  labels:
    app: store-app
spec:
  replicas: 4
  selector:
    matchLabels:
      pod: web06-pod
  template:
    metadata:
      labels:
        pod: web06-pod 
    spec:
      containers:
        - image: nginx:1.24 
          name: web-app 
          ports:
            - protocol: TCP
              containerPort: 8080
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: disktype
                    operator: In
                    values:
                      - ssd


