# Exercise 07-04 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web03-deploy 
  labels:
    app: store-app
spec:
  replicas: 4
  selector:
    matchLabels:
      pod: web03-pod
  template:
    metadata:
      labels:
        pod: web03-pod 
    spec:
      containers:
        - image: nginx:1.24 
          name: web-app 
          ports:
            - protocol: TCP
              containerPort: 8080
      affinity:        
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: disktype
                  operator: In
                  values:
                    - hdd 
                    - ssd
