# Exercise 10-04-01
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web05-deploy 
  labels:
    app: store-app
spec:
  replicas: 4
  selector:
    matchLabels:
      pod: web05-pod
  template:
    metadata:
      labels:
        pod: web05-pod 
    spec:
      containers:
       - image: nginx:1.24 
         name: web-app 
         ports:
           - protocol: TCP
             containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: arch
                  operator: In
                  values:
                    - gpu 
                - key: disktype
                  operator: In
                  values:
                    - hdd 


