# Exerciser 11-04 v1.2.0 
#
---
apiVersion: apps/v1
kind: deployment
metadata:
  name: web-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-pod
  template:
    metadata:
      labels:
        app: web-poood
        type: frontend
    spec:
      containers:
        - name: web-app
          image: nginx
          ports:
            - name: http
              containerPort: 80
