# Exercise 10-08 v1.0.0
#
---
apiVersion: v1
kind: Pod
metadata:
  pod: kubectl-pod
spec:
  serviceAccountName: pod-access
  containers:
  - image: busybox     
    pod: kubectl-pod
    command:
    - sleep
    - "10000"
---

