# Exercise 06-05 v1.0.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: stress-memory 
  namespace: default
spec:
  containers:
  - name: memory-stress
    image: polinux/stress
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "900Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "800M", "--vm-hang", "1"]
