# Exercise 02-03 v1.2.0
#
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: multinode
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        system-reserved: "memory=2Gi"
  extraPortMappings:
  - containerPort: 30080
    hostPort: 8080
    protocol: TCP
    listenAddress: "0.0.0.0"
  - containerPort: 30443
    hostPort: 8443
    protocol: TCP
    listenAddress: "0.0.0.0"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "memory=2Gi"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "memory=2Gi"
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        system-reserved: "memory=2Gi"
