# Exercise 17-05 v1.0.0
#
---
apiVersion: v1
kind: Namespace
metadata:
  name: prdstore-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web07-deploy
  namespace: prdstore-ns
  labels:
    app: store-app 
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      pod: web07-pod
  template:
    metadata:
      labels:
        pod: web07-pod
    spec:
      containers:
        - name: web-app
#          image: nginx:1.24
          image: parthcldr/cloudera-ingress-example-image
          ports:
            - name: http 
              containerPort: 80
              protocol: TCP
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web07-svc
  namespace: prdstore-ns
  labels:
    app: store-app
    tier: frontend
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    pod: web07-pod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
