# Exercise 15-06 v1.2.0
#
---
apiVersion: v1
kind: Pod
metadata:
  name: web03-pod 
spec:
  containers:
  - name: web-app 
    image: nginx
    resources:
      requests:
        cpu: "400m"
        memory: "20Mi"
      limits:
        cpu: "800m"
        memory: "40Mi"

