# Exercise 20-04 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app10-deploy 
  namespace: devstore-ns
  labels:
    app: store-app
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: app10-pod
  template:
    metadata:
      labels:
        pod: app10-pod
        tier: frontend
    spec:
      containers:
        - name: store-app
          image: node:21-alpine
          command: ['sh', '-c', "sleep 3000"]
          ports:
            - containerPort: 3000
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app10-svc
  namespace: devstore-ns
  labels:
    app: store-app
    tier: frontend
spec:
  type: ClusterIP 
  selector:
    pod: app10-pod
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
