# Exercise 20-03 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web10-deploy
  namespace: devstore-ns
  labels:
    app: store-app
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: web10-pod
  template:
    metadata:
      labels:
        pod: web10-pod
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx:1.21-alpine
          ports:
          - containerPort: 80
          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: web10-svc
  namespace: devstore-ns
  labels:
    app: store-app
    tier: frontend
spec:
  type: ClusterIP
  selector:
    pod: web10-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
