# Exercise 07-05 v1.0.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web11-deploy
  labels:
    app: store-app 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web11-pod
  template:
    metadata:
      labels:
        app: web11-pod
    spec:
      containers:
      - name: web-app
        image: nginx:1.24
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - prdfin 
            topologyKey: "kubernetes.io/hostname"
            namespaceSelector: {}
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - prdsam 
            topologyKey: "kubernetes.io/hostname"
            namespaceSelector: {}