# Exercise 12-04 v1.0.0
#
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-sc-adm-cr
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-sc-adm-crb
  namespace: prdfin-ns
subjects:
- kind: ServiceAccount
  name: fin01-sa 
  namespace: prdfin-ns
roleRef:
  kind: ClusterRole
  name: pv-sc-adm-cr
  apiGroup: rbac.authorization.k8s.io

