apiVersion: v1
kind: ConfigMap
metadata:
  name: db-cm
data:
  db_host: mysql-worker
---
apiVersion: v1
kind: Secret
metadata:
  name: db01-secret
type: Opaque
data:
  username: dXNlcm5hbWU=
  password: cGFc3dcmQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db01-deploy 
  labels:
    app: store-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db01-pod
  template:
    metadata:
      labels:
        pod: db01-pod 
    spec:
      containers:
      - name: db-app 
        image: busybox:1.28
        command: ['sh', '-c', "printenv MYSQL_USER MYSQL_PASSWORD MYSQL_SERVER"]
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db01-sec
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db01-sec
              key: PASSWORD
        - name: MYSQL_SERVER 
          valueFrom: 
            configMapKeyRef:
              name: db01-config
              key: db_host
